image:
  file: .gitpod.Dockerfile
tasks:
  - name: Compile Plugin
    init: ./gradlew build
    command: "nodemon --watch src/ --exec \"./gradlew build && cp build/libs/*.jar server/plugins/\" --ext java,yml"
  - name: "Create Server"
    init: scripts/build_server.sh
    command: cd server && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -jar server.jar